# ----
# GitHub Pages

lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# ----
# Site

title: Hydra Template
url: "https://proud-alligator.cloudvent.net"
baseurl:
google_analytics_key: UA-46121892-5

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Product marketing template for Jekyll.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Hydra Template
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

timezone: Etc/UTC

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "documentation.html"
    values:
      layout: "page"
      full_width: true
  -
    scope:
      path: "contact.html"
    values:
      layout: "page"
      full_width: true

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
